### ISSUE TITLE
Versão PHP - [INFO]

### ISSUE THREAD

**Issue by reginaldojunior** [clubedaentrega/municipios-ibge#1]
Usei a base do seu código para fazer uma versão em PHP.

https://github.com/reginaldojunior/municipios-ibge

**Comment by sitegui** [comment]
Ok, mas talvez você queira atualizar os dados, já que eles estão há 3 anos sem serem renovados.

**Comment by reginaldojunior** [comment]
Ok, farei isso :smile:
